import type { HDGateData } from './types';

export const ALL_HD_GATES: Record<number, HDGateData> = {
  1: {
    gate: 1,
    iChingName: 'Das Schöpferische (Qian)',
    hexagramSymbol: '䷀',
    keynote: 'Selbstausdruck & Schöpferkraft',
    center: 'gCenter',
    channelId: '1-8',
    lightGift: 'Frische, originelle Schöpfungskraft und Inspiration',
    shadowFrequency: 'Entropie, Erstarrung und Angst vor Mittelmäßigkeit',
    siddhicPotential: 'Reine göttliche Schöpfung (Schönheit)'
  },
  2: {
    gate: 2,
    iChingName: 'Das Empfangende (Kun)',
    hexagramSymbol: '䷁',
    keynote: 'Höhere Richtung & Empfänglichkeit',
    center: 'gCenter',
    channelId: '2-14',
    lightGift: 'Orientierung, Vertrauen in die Lebensführung und Führungskraft',
    shadowFrequency: 'Verlorenheit, Orientierungslosigkeit und Mangelgefühl',
    siddhicPotential: 'Einheit mit dem Kosmos (Bedingungslose Hingabe)'
  },
  3: {
    gate: 3,
    iChingName: 'Die Anfangsschwierigkeit (Chun)',
    hexagramSymbol: '䷂',
    keynote: 'Ordnung aus dem Chaos (Innovation)',
    center: 'sacral',
    channelId: '3-60',
    lightGift: 'Mutation, spielerische Problemlösung und Neubeginn',
    shadowFrequency: 'Chaos, Resignation und Überforderung bei Veränderungen',
    siddhicPotential: 'Unschuld (Kosmische Ordnung)'
  },
  4: {
    gate: 4,
    iChingName: 'Die Jugendtorheit (Meng)',
    hexagramSymbol: '䷃',
    keynote: 'Formeln & Logische Antworten',
    center: 'ajna',
    channelId: '63-4',
    lightGift: 'Verständnis, formulieren tragfähiger Theorien und Lösungen',
    shadowFrequency: 'Besserwisserei, mentale Unruhe und Rechthaberei',
    siddhicPotential: 'Allumfassende Vergebung'
  },
  5: {
    gate: 5,
    iChingName: 'Das Warten (Xu)',
    hexagramSymbol: '䷄',
    keynote: 'Feste Rhythmen & Naturgesetze',
    center: 'sacral',
    channelId: '15-5',
    lightGift: 'Geduld, Einbettung in universelle Zeitzyklen und Vertrauen',
    shadowFrequency: 'Ungeduld, inneres Getriebensein und Hektik',
    siddhicPotential: 'Zeitlosigkeit'
  },
  6: {
    gate: 6,
    iChingName: 'Der Streit (Song)',
    hexagramSymbol: '䷅',
    keynote: 'Reibung & Intimitäts-Filter',
    center: 'solarPlexus',
    channelId: '6-59',
    lightGift: 'Diplomatie, emotionale Grenzsetzung und Reife',
    shadowFrequency: 'Konfliktsucht, Reizbarkeit und emotionale Kälte',
    siddhicPotential: 'Kosmischer Friede'
  },
  7: {
    gate: 7,
    iChingName: 'Das Heer (Shi)',
    hexagramSymbol: '䷆',
    keynote: 'Rolle des Selbst in der Führung',
    center: 'gCenter',
    channelId: '7-31',
    lightGift: 'Demokratische Führung, Weitsicht und Führung durch Dienen',
    shadowFrequency: 'Autoritarismus, Diktatur oder Machtlosigkeit',
    siddhicPotential: 'Tugend'
  },
  8: {
    gate: 8,
    iChingName: 'Der Zusammenhalt (Bi)',
    hexagramSymbol: '䷇',
    keynote: 'Beitrag & Förderung des Neuen',
    center: 'throat',
    channelId: '1-8',
    lightGift: 'Vorbildwirkung, Förderung einzigartiger Talente',
    shadowFrequency: 'Konformismus, Anpassung aus Furcht vor Ausgrenzung',
    siddhicPotential: 'Erhabenheit'
  },
  9: {
    gate: 9,
    iChingName: 'Die Deszendenz des Kleinen (Xiao Chu)',
    hexagramSymbol: '䷈',
    keynote: 'Fokus auf das Detail',
    center: 'sacral',
    channelId: '9-52',
    lightGift: 'Zielgerichteter Fokus, Beharrlichkeit und Gründlichkeit',
    shadowFrequency: 'Trägheit, Verzetteln in unwichtigen Kleinigkeiten',
    siddhicPotential: 'Unbesiegbarkeit'
  },
  10: {
    gate: 10,
    iChingName: 'Das Auftreten (Lu)',
    hexagramSymbol: '䷉',
    keynote: 'Selbstliebe & Verhalten des Selbst',
    center: 'gCenter',
    channelId: '10-20',
    lightGift: 'Natürlichkeit, Selbstakzeptanz und authentisches Vorbild',
    shadowFrequency: 'Selbsthass, Anmaßung oder narzisstische Abkapselung',
    siddhicPotential: 'Sein (Reine Gegenwärtigkeit)'
  },
  11: {
    gate: 11,
    iChingName: 'Der Friede (Tai)',
    hexagramSymbol: '䷊',
    keynote: 'Ideen & Philosophische Visionen',
    center: 'ajna',
    channelId: '11-56',
    lightGift: 'Idealismus, Fülle an konzeptionellen Visionen und Einsichten',
    shadowFrequency: 'Illusionen, Realitätsflucht und Ideenüberflutung',
    siddhicPotential: 'Erleuchtetes Licht'
  },
  12: {
    gate: 12,
    iChingName: 'Der Stillstand (Pi)',
    hexagramSymbol: '䷋',
    keynote: 'Vorsicht & Zurückhaltung',
    center: 'throat',
    channelId: '12-22',
    lightGift: 'Diskretion, feinsinniger poetischer Ausdruck und Anmut',
    shadowFrequency: 'Eitelkeit, Zynismus und emotionale Verschlossenheit',
    siddhicPotential: 'Reinheit'
  },
  13: {
    gate: 13,
    iChingName: 'Die Gemeinschaft mit Menschen (Tong Ren)',
    hexagramSymbol: '䷌',
    keynote: 'Zuhören & Hüter der Geheimnisse',
    center: 'gCenter',
    channelId: '13-33',
    lightGift: 'Empathisches Zuhören, Sammeln von Weisheiten',
    shadowFrequency: 'Indiskretion, Verbitterung oder emotionale Taubheit',
    siddhicPotential: 'Kosmische Empathie'
  },
  14: {
    gate: 14,
    iChingName: 'Der Besitz von Großem (Da You)',
    hexagramSymbol: '䷍',
    keynote: 'Machtvolle Fähigkeiten & Wohlstand',
    center: 'sacral',
    channelId: '2-14',
    lightGift: 'Kompetenz, fruchtbare Schaffenskraft und Wohlstandsförderung',
    shadowFrequency: 'Kompromissler, Ausbeutung und Ressourcenverschwendung',
    siddhicPotential: 'Grenzenlose Fülle'
  },
  15: {
    gate: 15,
    iChingName: 'Die Bescheidenheit (Qian)',
    hexagramSymbol: '䷎',
    keynote: 'Extreme Rhythmen & Menschenliebe',
    center: 'gCenter',
    channelId: '15-5',
    lightGift: 'Magnetismus, Flexibilität und Akzeptanz aller Lebensarten',
    shadowFrequency: 'Monotonie, Langeweile oder chaotischer Aktionismus',
    siddhicPotential: 'Blühende Menschlichkeit'
  },
  16: {
    gate: 16,
    iChingName: 'Die Begeisterung (Yu)',
    hexagramSymbol: '䷏',
    keynote: 'Fertigkeiten & Begeisterung',
    center: 'throat',
    channelId: '16-48',
    lightGift: 'Vielseitigkeit, handwerkliche Meisterschaft und Talent',
    shadowFrequency: 'Oberflächlichkeit, Unbeholfenheit und Scheinwissen',
    siddhicPotential: 'Meisterschaft'
  },
  17: {
    gate: 17,
    iChingName: 'Die Nachfolge (Sui)',
    hexagramSymbol: '䷐',
    keynote: 'Meinungen & Konzepte für die Zukunft',
    center: 'ajna',
    channelId: '17-62',
    lightGift: 'Weitsicht, Formulierung logischer Perspektiven und Systeme',
    shadowFrequency: 'Dogmatismus, Engstirnigkeit und Vorurteile',
    siddhicPotential: 'Allwissenheit'
  },
  18: {
    gate: 18,
    iChingName: 'Die Arbeit am Verdorbenen (Gu)',
    hexagramSymbol: '䷑',
    keynote: 'Korrektur & Verfeinerung',
    center: 'spleen',
    channelId: '18-58',
    lightGift: 'Integrität, therapeutischer Blick und Perfektionierung',
    shadowFrequency: 'Urteilsucht, chronisches Kritisieren und Mängelfokus',
    siddhicPotential: 'Vollkommenheit'
  },
  19: {
    gate: 19,
    iChingName: 'Die Annäherung (Lin)',
    hexagramSymbol: '䷒',
    keynote: 'Bedürfnisse & Feinfühligkeit',
    center: 'root',
    channelId: '49-19',
    lightGift: 'Sensibilität, Fürsorge für die Schwachen und Zusammenhalt',
    shadowFrequency: 'Abhängigkeit, Bedürftigkeit und Klammern',
    siddhicPotential: 'Heilige Hingabe'
  },
  20: {
    gate: 20,
    iChingName: 'Die Betrachtung (Guan)',
    hexagramSymbol: '䷓',
    keynote: 'Gegenwärtigkeit & Kontemplation',
    center: 'throat',
    channelId: '20-34',
    lightGift: 'Selbstbewusstheit im Jetzt, klares spontanes Reagieren',
    shadowFrequency: 'Oberflächlichkeit, Hektik und mentale Zerstreuung',
    siddhicPotential: 'Reine Gegenwart'
  },
  21: {
    gate: 21,
    iChingName: 'Das Durchbeißen (Shi Ke)',
    hexagramSymbol: '䷔',
    keynote: 'Kontrolle & Ressourcen-Steuerung',
    center: 'heart',
    channelId: '21-45',
    lightGift: 'Autorität, gerechte Verteilung und Führungsstärke',
    shadowFrequency: 'Kontrollwahn, Unterdrückung und Machtkämpfe',
    siddhicPotential: 'Tapferkeit'
  },
  22: {
    gate: 22,
    iChingName: 'Die Anmut (Bi)',
    hexagramSymbol: '䷕',
    keynote: 'Offenheit & Emotionale Eleganz',
    center: 'solarPlexus',
    channelId: '12-22',
    lightGift: 'Anmut, soziale Wärme und emotionale Großzügigkeit',
    shadowFrequency: 'Unehrenhaftigkeit, Launenhaftigkeit und Taktlosigkeit',
    siddhicPotential: 'Gnade'
  },
  23: {
    gate: 23,
    iChingName: 'Die Zerspaltung (Bo)',
    hexagramSymbol: '䷖',
    keynote: 'Assimilation & Einfachheit',
    center: 'throat',
    channelId: '43-23',
    lightGift: 'Klarheit, geniale Vereinfachung des Unverständlichen',
    shadowFrequency: 'Wirrwarr, Zersplitterung und abstruse Erklärungen',
    siddhicPotential: 'Quintessenz'
  },
  24: {
    gate: 24,
    iChingName: 'Die Wiederkehr (Fu)',
    hexagramSymbol: '䷗',
    keynote: 'Rationalisierung & Erneuerung',
    center: 'ajna',
    channelId: '61-24',
    lightGift: 'Erfindungsgabe, Reorganisation und Geistesblitze',
    shadowFrequency: 'Sucht nach Antworten, endlose Gedankenschleifen',
    siddhicPotential: 'Stille'
  },
  25: {
    gate: 25,
    iChingName: 'Die Unschuld (Wu Wang)',
    hexagramSymbol: '䷘',
    keynote: 'Universelle Liebe & Geist des Ganzen',
    center: 'gCenter',
    channelId: '25-51',
    lightGift: 'Akzeptanz, Reinheit des Herzens und bedingungslose Liebe',
    shadowFrequency: 'Verengung, Kälte und Schockstarre',
    siddhicPotential: 'Universelle Unschuld'
  },
  26: {
    gate: 26,
    iChingName: 'Des Großen Zähmungskraft (Da Chu)',
    hexagramSymbol: '䷙',
    keynote: 'Der Trickster / Akkumulator von Kraft',
    center: 'heart',
    channelId: '26-44',
    lightGift: 'Geschicklichkeit, Überzeugungskraft und Effizienz',
    shadowFrequency: 'Prahlerei, Manipulation und Lügen',
    siddhicPotential: 'Unsichtbarkeit'
  },
  27: {
    gate: 27,
    iChingName: 'Die Ernährung (Yi)',
    hexagramSymbol: '䷚',
    keynote: 'Fürsorge & Bewahrung',
    center: 'sacral',
    channelId: '27-50',
    lightGift: 'Altruismus, liebevolle Pflege und Stärkung anderer',
    shadowFrequency: 'Selbstaufopferung, Gier oder Vernachlässigung',
    siddhicPotential: 'Selbstlosigkeit'
  },
  28: {
    gate: 28,
    iChingName: 'Des Großen Übergewicht (Da Guo)',
    hexagramSymbol: '䷛',
    keynote: 'Der Spieler / Suche nach Sinn',
    center: 'spleen',
    channelId: '28-38',
    lightGift: 'Zähigkeit, Sinnfindung und furchtloser Lebensmut',
    shadowFrequency: 'Sinnlosigkeit, Todesfurcht und sinnlose Risiken',
    siddhicPotential: 'Unsterblichkeit'
  },
  29: {
    gate: 29,
    iChingName: 'Das Abgründige (Kan)',
    hexagramSymbol: '䷜',
    keynote: 'Das Ja zum Leben (Hingabe)',
    center: 'sacral',
    channelId: '46-29',
    lightGift: 'Zuverlässigkeit, Ausdauer und totale Hingabe an Aufgaben',
    shadowFrequency: 'Halbherzigkeit, Überlastung durch falsche Zusagen',
    siddhicPotential: 'Ergebenheit'
  },
  30: {
    gate: 30,
    iChingName: 'Das Haftende (Li)',
    hexagramSymbol: '䷝',
    keynote: 'Feuer des Verlangens & Schicksal',
    center: 'solarPlexus',
    channelId: '30-41',
    lightGift: 'Leichtigkeit, Akzeptanz des Schicksals und Lebensfeuer',
    shadowFrequency: 'Begierde, Frustration über unerfüllbare Sehnsüchte',
    siddhicPotential: 'Verzückung'
  },
  31: {
    gate: 31,
    iChingName: 'Die Einwirkung (Xian)',
    hexagramSymbol: '䷞',
    keynote: 'Führung durch Sprache & Einfluss',
    center: 'throat',
    channelId: '7-31',
    lightGift: 'Inspirierende Rede, Führung auf Augenhöhe',
    shadowFrequency: 'Arroganz, Demagogie und manipulativer Einfluss',
    siddhicPotential: 'Demut'
  },
  32: {
    gate: 32,
    iChingName: 'Die Dauer (Heng)',
    hexagramSymbol: '䷟',
    keynote: 'Kontinuität & Anpassungsfähigkeit',
    center: 'spleen',
    channelId: '32-54',
    lightGift: 'Ausdauer, Gespür für beständige Werte und Trends',
    shadowFrequency: 'Versagensangst, Festhalten an toten Traditionen',
    siddhicPotential: 'Erhabenheit'
  },
  33: {
    gate: 33,
    iChingName: 'Der Rückzug (Dun)',
    hexagramSymbol: '䷠',
    keynote: 'Privatsphäre & Erinnerung',
    center: 'throat',
    channelId: '13-33',
    lightGift: 'Achtsamkeit, Reflexion und Bewahrung von Lebenserfahrung',
    shadowFrequency: 'Vergessen, Flucht vor der Realität und Groll',
    siddhicPotential: 'Offenbarung'
  },
  34: {
    gate: 34,
    iChingName: 'Des Großen Macht (Da Zhuang)',
    hexagramSymbol: '䷡',
    keynote: 'Reine Macht & vitale Kraft',
    center: 'sacral',
    channelId: '20-34',
    lightGift: 'Stärke, kraftvolles Schaffen im Einklang mit dem Ganzen',
    shadowFrequency: 'Gewalt, rücksichtsloser Kraftaufwand',
    siddhicPotential: 'Majestät'
  },
  35: {
    gate: 35,
    iChingName: 'Der Fortschritt (Jin)',
    hexagramSymbol: '䷢',
    keynote: 'Veränderung & Sammeln von Erfahrungen',
    center: 'throat',
    channelId: '35-36',
    lightGift: 'Abenteuerlust, Innovationsfreude und Vielseitigkeit',
    shadowFrequency: 'Hunger nach Sensationen, Enttäuschung über Stillstand',
    siddhicPotential: 'Grenzenlosigkeit'
  },
  36: {
    gate: 36,
    iChingName: 'Die Verfinsterung des Lichts (Ming Yi)',
    hexagramSymbol: '䷣',
    keynote: 'Krisenbewältigung & Emotionale Tiefe',
    center: 'solarPlexus',
    channelId: '35-36',
    lightGift: 'Menschlichkeit, Resilienz in Krisen und Wandlungskraft',
    shadowFrequency: 'Turbulenzen, emotionale Verzweiflung und Drama',
    siddhicPotential: 'Mitgefühl'
  },
  37: {
    gate: 37,
    iChingName: 'Die Sippe (Jia Ren)',
    hexagramSymbol: '䷤',
    keynote: 'Familie, Herzenswärme & Freundschaft',
    center: 'solarPlexus',
    channelId: '40-37',
    lightGift: 'Gleichberechtigung, Loyalität und familiäre Harmonie',
    shadowFrequency: 'Schwäche, sentimentale Abhängigkeit und Eifersucht',
    siddhicPotential: 'Zärtlichkeit'
  },
  38: {
    gate: 38,
    iChingName: 'Der Gegensatz (Kui)',
    hexagramSymbol: '䷥',
    keynote: 'Der Kämpfer / Mut zur Integrität',
    center: 'root',
    channelId: '28-38',
    lightGift: 'Beharrlichkeit, mutiges Eintreten für Werte und Sinn',
    shadowFrequency: 'Streitsucht, Aggression und sturer Trotz',
    siddhicPotential: 'Ehre'
  },
  39: {
    gate: 39,
    iChingName: 'Das Hemmnis (Jian)',
    hexagramSymbol: '䷦',
    keynote: 'Provokation & Befreiung von Blockaden',
    center: 'root',
    channelId: '55-39',
    lightGift: 'Dynamik, das Wecken von Lebensgeistern und Befreiung',
    shadowFrequency: 'Provokation, emotionale Härte und Zynismus',
    siddhicPotential: 'Befreiung'
  },
  40: {
    gate: 40,
    iChingName: 'Die Befreiung (Xie)',
    hexagramSymbol: '䷧',
    keynote: 'Alleinsein & Hingabe an den Stamm',
    center: 'heart',
    channelId: '40-37',
    lightGift: 'Entspannung, Verlässlichkeit und Großzügigkeit',
    shadowFrequency: 'Erschöpfung, Einsamkeit und Groll über Ausnutzung',
    siddhicPotential: 'Göttlicher Wille'
  },
  41: {
    gate: 41,
    iChingName: 'Die Minderung (Sun)',
    hexagramSymbol: '䷨',
    keynote: 'Start-Codon / Fantasie & Verlangen',
    center: 'root',
    channelId: '30-41',
    lightGift: 'Visionskraft, Initiierung neuer energetischer Zyklen',
    shadowFrequency: 'Fantasielosigkeit, Verbitterung über Unerfülltes',
    siddhicPotential: 'Emanation'
  },
  42: {
    gate: 42,
    iChingName: 'Die Mehrung (Yi)',
    hexagramSymbol: '䷩',
    keynote: 'Abschluss & Reifung von Zyklen',
    center: 'sacral',
    channelId: '42-53',
    lightGift: 'Vollendung, Loslassen und Ernte des Gelernten',
    shadowFrequency: 'Festhalten an Überholtem, Angst vor dem Ende',
    siddhicPotential: 'Feier des Lebens'
  },
  43: {
    gate: 43,
    iChingName: 'Der Durchbruch (Guai)',
    hexagramSymbol: '䷪',
    keynote: 'Einsicht & Das innere Ohr',
    center: 'ajna',
    channelId: '43-23',
    lightGift: 'Genialität, intuitive Durchbrüche und Originalität',
    shadowFrequency: 'Taubheit für Argumente, sture Gedankenstarre',
    siddhicPotential: 'Erleuchtung'
  },
  44: {
    gate: 44,
    iChingName: 'Das Entgegenkommen (Gou)',
    hexagramSymbol: '䷫',
    keynote: 'Wachsamkeit & Zusammenarbeit',
    center: 'spleen',
    channelId: '26-44',
    lightGift: 'Synergie, hervorragende Menschenkenntnis und Instinkt',
    shadowFrequency: 'Misstrauen, Angst vor der Wiederholung alter Fehler',
    siddhicPotential: 'Menschliche Eintracht'
  },
  45: {
    gate: 45,
    iChingName: 'Die Sammlung (Cui)',
    hexagramSymbol: '䷬',
    keynote: 'Der Sammler / König der Fülle',
    center: 'throat',
    channelId: '21-45',
    lightGift: 'Synergie, Schirmherrschaft und Erhalt des Wohlstands',
    shadowFrequency: 'Dominanz, Geiz und Besitzdenken',
    siddhicPotential: 'Synergie'
  },
  46: {
    gate: 46,
    iChingName: 'Das Empordringen (Sheng)',
    hexagramSymbol: '䷭',
    keynote: 'Liebe zum Körper & Glück des Augenblicks',
    center: 'gCenter',
    channelId: '46-29',
    lightGift: 'Hingabe an den physischen Tempel, glückliche Fügungen',
    shadowFrequency: 'Körperabneigung, Scham oder ständiges Hadern',
    siddhicPotential: 'Ekstase'
  },
  47: {
    gate: 47,
    iChingName: 'Die Bedrängnis (Kun)',
    hexagramSymbol: '䷮',
    keynote: 'Realisierung & Verstehen der Vergangenheit',
    center: 'ajna',
    channelId: '64-47',
    lightGift: 'Verwandlung, Sinnfindung und Durchdringen von Rätseln',
    shadowFrequency: 'Unterdrückung, mentale Hoffnungslosigkeit',
    siddhicPotential: 'Verklärung'
  },
  48: {
    gate: 48,
    iChingName: 'Der Brunnen (Jing)',
    hexagramSymbol: '䷯',
    keynote: 'Tiefe Weisheit & Lösungen',
    center: 'spleen',
    channelId: '16-48',
    lightGift: 'Einfallsreichtum, unerschöpfliches Fachwissen',
    shadowFrequency: 'Unzulänglichkeit, Angst vor mangelndem Wissen',
    siddhicPotential: 'Weisheit'
  },
  49: {
    gate: 49,
    iChingName: 'Die Umwälzung (Ge)',
    hexagramSymbol: '䷰',
    keynote: 'Revolution & Gerechte Prinzipien',
    center: 'solarPlexus',
    channelId: '49-19',
    lightGift: 'Gerechtigkeit, Reformgeist und Transformation',
    shadowFrequency: 'Reaktionismus, emotionale Härte und Intoleranz',
    siddhicPotential: 'Wiedergeburt'
  },
  50: {
    gate: 50,
    iChingName: 'Der Tiegel (Ding)',
    hexagramSymbol: '䷱',
    keynote: 'Werte, Gesetze & Schutz',
    center: 'spleen',
    channelId: '27-50',
    lightGift: 'Gleichgewicht, Hüten von Tradition und Lebensqualität',
    shadowFrequency: 'Korruption, Vernachlässigung von Regeln und Werten',
    siddhicPotential: 'Harmonie'
  },
  51: {
    gate: 51,
    iChingName: 'Das Erregende (Zhen)',
    hexagramSymbol: '䷲',
    keynote: 'Der Schock / Mut zum Erwachen',
    center: 'heart',
    channelId: '25-51',
    lightGift: 'Initiative, Kühnheit und spiritueller Pioniergeist',
    shadowFrequency: 'Feigheit, Erstarrung oder unnötige Risikolust',
    siddhicPotential: 'Erwachen'
  },
  52: {
    gate: 52,
    iChingName: 'Das Stillehalten (Gen)',
    hexagramSymbol: '䷳',
    keynote: 'Der ruhende Berg / Stille Kraft',
    center: 'root',
    channelId: '9-52',
    lightGift: 'Gelassenheit, Konzentration und meditative Ruhe',
    shadowFrequency: 'Stress, Ruhelosigkeit oder lähmende Apathie',
    siddhicPotential: 'Stille'
  },
  53: {
    gate: 53,
    iChingName: 'Die Entwicklung (Jian)',
    hexagramSymbol: '䷴',
    keynote: 'Neuanfang & Entwicklungsschritte',
    center: 'root',
    channelId: '42-53',
    lightGift: 'Initiierungskraft, Neugier und Aufbruchsbereitschaft',
    shadowFrequency: 'Unreife, voreiliges Beginnen ohne Durchhaltevermögen',
    siddhicPotential: 'Superabundanz'
  },
  54: {
    gate: 54,
    iChingName: 'Das heiratende Mädchen (Gui Mei)',
    hexagramSymbol: '䷵',
    keynote: 'Ehrgeiz & Spiritueller Aufstieg',
    center: 'root',
    channelId: '32-54',
    lightGift: 'Zielstrebigkeit, Tatkraft und Wandlung des Ehrgeizes',
    shadowFrequency: 'Geltungssucht, Verbissenheit und Neid',
    siddhicPotential: 'Erleuchtung'
  },
  55: {
    gate: 55,
    iChingName: 'Die Fülle (Feng)',
    hexagramSymbol: '䷶',
    keynote: 'Seelengeist & Emotionale Freiheit',
    center: 'solarPlexus',
    channelId: '55-39',
    lightGift: 'Füllebewusstsein, emotionale Romantik und Musikalität',
    shadowFrequency: 'Viktimisierung, Melancholie und emotionale Leere',
    siddhicPotential: 'Freiheit'
  },
  56: {
    gate: 56,
    iChingName: 'Der Wanderer (Lu)',
    hexagramSymbol: '䷷',
    keynote: 'Der Geschichtenerzähler / Reisedrang',
    center: 'throat',
    channelId: '11-56',
    lightGift: 'Beredsamkeit, Lebensphilosophie und Inspiration',
    shadowFrequency: 'Zerstreuung, Geschwätzigkeit und Reizüberflutung',
    siddhicPotential: 'Trunkenheit des Geistes'
  },
  57: {
    gate: 57,
    iChingName: 'Das Sanfte (Sun)',
    hexagramSymbol: '䷸',
    keynote: 'Intuitive Klarheit & Das Gehör',
    center: 'spleen',
    channelId: '10-57',
    lightGift: 'Hellsichtige Intuition, Wahrnehmung feiner Schwingungen',
    shadowFrequency: 'Zukunftsangst, Nervosität und Misstrauen',
    siddhicPotential: 'Klarheit'
  },
  58: {
    gate: 58,
    iChingName: 'Das Heitere (Dui)',
    hexagramSymbol: '䷹',
    keynote: 'Lebensfreude & Drang zur Vollendung',
    center: 'root',
    channelId: '18-58',
    lightGift: 'Vitalität, Optimismus und ansteckende Begeisterung',
    shadowFrequency: 'Unzufriedenheit, zynische Kritiksucht',
    siddhicPotential: 'Glückseligkeit'
  },
  59: {
    gate: 59,
    iChingName: 'Die Auflösung (Huan)',
    hexagramSymbol: '䷺',
    keynote: 'Intimität & Durchdringung von Mauern',
    center: 'sacral',
    channelId: '6-59',
    lightGift: 'Herzensöffnung, vertrauensvolle Nähe und Bindung',
    shadowFrequency: 'Unehrlichkeit, Grenzverletzung oder Abkapselung',
    siddhicPotential: 'Transparenz'
  },
  60: {
    gate: 60,
    iChingName: 'Die Beschränkung (Jie)',
    hexagramSymbol: '䷻',
    keynote: 'Grenzen & Akzeptanz des Rahmens',
    center: 'root',
    channelId: '3-60',
    lightGift: 'Strukturtreue, schöpferische Kraft innerhalb von Grenzen',
    shadowFrequency: 'Rigidität, Depression und Kampf gegen Notwendigkeiten',
    siddhicPotential: 'Gerechtigkeit'
  },
  61: {
    gate: 61,
    iChingName: 'Innere Wahrheit (Zhong Fu)',
    hexagramSymbol: '䷼',
    keynote: 'Das Mysterium & Innere Gewissheit',
    center: 'head',
    channelId: '61-24',
    lightGift: 'Inspiration, Ergründung der großen Geheimnisse des Lebens',
    shadowFrequency: 'Psychose, Zwanghaftigkeit und Grübelzwang',
    siddhicPotential: 'Heiligkeit'
  },
  62: {
    gate: 62,
    iChingName: 'Des Kleinen Übergewicht (Xiao Guo)',
    hexagramSymbol: '䷽',
    keynote: 'Präzision & Benennen der Fakten',
    center: 'throat',
    channelId: '17-62',
    lightGift: 'Präzision, didaktische Klarheit und Formulierungskunst',
    shadowFrequency: 'Pedanterie, Wortklauberei und Rechthaberei',
    siddhicPotential: 'Makellosigkeit'
  },
  63: {
    gate: 63,
    iChingName: 'Nach der Vollendung (Ji Ji)',
    hexagramSymbol: '䷾',
    keynote: 'Zweifel & Logische Überprüfung',
    center: 'head',
    channelId: '63-4',
    lightGift: 'Wahrheitsfindung, wissenschaftlicher Scharfsinn',
    shadowFrequency: 'Selbstzweifel, Argwohn und quälende Unsicherheit',
    siddhicPotential: 'Wahrheit'
  },
  64: {
    gate: 64,
    iChingName: 'Vor der Vollendung (Wei Ji)',
    hexagramSymbol: '䷿',
    keynote: 'Bilderflut & Sinnsuche',
    center: 'head',
    channelId: '64-47',
    lightGift: 'Vorstellungskraft, Verwandlung von Erlebtem in Kunst',
    shadowFrequency: 'Verwirrung, Überflutung durch alte Erinnerungen',
    siddhicPotential: 'Erleuchtung'
  }
};

export function getGateData(gate: number): HDGateData {
  return ALL_HD_GATES[gate] || {
    gate,
    iChingName: `Tor ${gate}`,
    hexagramSymbol: '☰',
    keynote: 'Kosmische Archetypenkraft',
    center: 'gCenter',
    channelId: '',
    lightGift: 'Entwicklung und Entfaltung',
    shadowFrequency: 'Unbewusstheit',
    siddhicPotential: 'Transzendenz'
  };
}
